spring:
    application:
        name: pokus-spring-state-machine
    datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
